# Generated by Django 5.1.7 on 2025-03-25 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SketchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('sketch', models.ImageField(blank=True, null=True, upload_to='sketches/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
