# Generated by Django 5.1.7 on 2025-03-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sketch', '0003_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
